version: '3'

services:
  orders-service-db:
    image: postgres:latest
    container_name: orders-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_service_db
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/db:/var/lib/postgresql/data
